---@diagnostic disable: undefined-global
---@
hl.config({ autogenerated = false })

local hs = require("hyprsplit")
hs.config({ num_workspaces = 10 })
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind("SUPER + " .. key, hs.dsp.focus({ workspace = i }))
	hl.bind("SUPER + SHIFT + " .. key, hs.dsp.window.move({ workspace = i, follow = true }))
end

hl.bind("SUPER + g", hs.dsp.grab_rogue_windows())
hl.bind("SUPER + tab", hs.dsp.workspace.swap_monitors({ monitor1 = "current", monitor2 = "+1" }))
