# ${path}: Full path to the currently playing file.
# ${filename}: Just the name of the file (without the path).
# ${time-pos}: The current playback position in seconds.
# ${working-directory}: The directory mpv was started from. 

ctrl+c run "wl-copy" "-t" "text/plain" "${path}"