windowrule {
	name = flameshot-overlay
	match:title = ^(flameshot)
	float = on
	move = (-1*monitor_w) 0
	size = (monitor_w*2) monitor_h
	monitor = HDMI-A-1
	pin = on
}

# windowrule {
# 	name = mpv-monitor-3
# 	match:class = mpv
# 	monitor = HDMI-A-1
# }