---@diagnostic disable: undefined-global
hl.config({ autogenerated = false })

local hs = require("hyprsplit")
hs.config({ num_workspaces = 10 })
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind("SUPER + " .. key, hs.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. key, hs.dsp.window.move({ workspace = i, follow = true }))
end

hl.bind("SUPER + " .. "g", hs.dsp.grab_rogue_windows())
hl.bind("SUPER + " .. "tab", hs.dsp.workspace.swap_monitors({ monitor1 = "current", monitor2 = "+1" }))

local profile = os.getenv("HYPR_PROFILE") or "computer"
local terminal = "foot"

-- --------------------------------------------------------------------------
-- Monitors
-- --------------------------------------------------------------------------
if profile == "laptop" then
    hl.monitor({ output = "HDMI-A-2", mode = "640x480@59.94Hz", position = "1920x0", scale = 1 })
    hl.monitor({ output = "eDP-1", mode = "1920x1080@60.00Hz", position = "0x0", scale = 1, sdr_eotf = 1 })
else
    hl.monitor({ output = "DP-1", mode = "1920x1080@74.97Hz", position = "0x0", scale = 1, sdr_eotf = 1 })
    hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@75.00Hz", position = "1920x0", scale = 1, sdr_eotf = 1 })
end

-- --------------------------------------------------------------------------
-- Environment and startup
-- --------------------------------------------------------------------------
hl.env("XCURSOR_SIZE", "32")
hl.env("XCURSOR_THEME", "Bibata-Rainbow-Modern")

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor Bibata-Rainbow-Modern 32")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme Bibata-Rainbow-Modern")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 32")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme prefer-dark")

    hl.exec_cmd("nu --login -c \"source ~/.config/nushell/login.nu\"")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("pkill --full --exact /usr/lib/xdg-desktop-portal")
    hl.exec_cmd("sleep 1.25s && hyprpm reload")
    hl.exec_cmd("sleep 2.00s && hyprctl reload")
    hl.exec_cmd("sleep 10s && dinitctl start fcitx5")
    hl.exec_cmd("sleep 5.25s && dinitctl start xdg-desktop-portal")
    hl.exec_cmd("sleep 2.00s && dinitctl start xdg-desktop-portal-hyprland")
    hl.exec_cmd("sleep 1.50s && dinitctl start awww-daemon")
    hl.exec_cmd("sleep 1.50s && dinitctl start nm-applet")
    hl.exec_cmd("sleep 2.50s && dinitctl start polkit-gnome-agent")
    hl.exec_cmd("sleep 1.50s && dinitctl start gammastep")
    hl.exec_cmd("sleep 1.50s && dinitctl start blueman-applet")
    hl.exec_cmd("sleep 1.50s && dinitctl start cliphist")
    hl.exec_cmd("sleep 1.50s && dinitctl start ags")
    hl.exec_cmd("sleep 1.50s && dinitctl start thunderbird")
    hl.exec_cmd("sleep 1.50s && dinitctl start flameshot")
    hl.exec_cmd("sleep 2.50s && dinitctl start beeper")
    hl.exec_cmd("sleep 2.25s && dinitctl start rclone-daemon")
end)

-- --------------------------------------------------------------------------
-- Main config blocks
-- --------------------------------------------------------------------------
hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 20,
        layout = "dwindle",
        border_size = 0,
    },
    decoration = {
        rounding = 8,
        dim_special = 0,
        shadow = {
            enabled = true,
            range = 36,
            render_power = 4,
            color = "rgba(00000044)",
        },
        blur = {
            enabled = true,
            xray = false,
            special = false,
            new_optimizations = true,
            size = 1,
            passes = 4,
            brightness = 1,
            noise = 0.01,
            contrast = 1,
            popups = true,
            popups_ignorealpha = 0.6,
        },
    },
    animations = {
        enabled = true,
    },
    cursor = {
        zoom_disable_aa = true,
        inactive_timeout = 4,
        hide_on_tablet = true,
        no_hardware_cursors = true,
    },
    dwindle = {
        preserve_split = true,
        force_split = 2,
        split_width_multiplier = 1.3,
    },
    ecosystem = {
        no_update_news = true,
    },
    debug = {
        disable_logs = true,
        damage_tracking = false,
    },
    input = {
        kb_layout = "br",
        kb_variant = "thinkpad",
        kb_model = "",
        kb_options = "",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
            disable_while_typing = true,
        },
        repeat_rate = 60,
        repeat_delay = 200,
    },
    misc = {
        middle_click_paste = false,
        force_default_wallpaper = -1,
        focus_on_activate = true,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = false,
        enable_swallow = false,
        disable_hyprland_logo = true,
    },
    xwayland = {
        use_nearest_neighbor = true,
        force_zero_scaling = true,
    },
    gestures = {
        workspace_swipe_create_new = true,
        workspace_swipe_forever = true,
        workspace_swipe_direction_lock = false,
    },
})

-- --------------------------------------------------------------------------
-- Animation curves and mappings
-- --------------------------------------------------------------------------
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("md3_standard", { type = "bezier", points = { { 0.2, 0 }, { 0, 1 } } })
hl.curve("md3_decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("md3_accel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })
hl.curve("crazyshot", { type = "bezier", points = { { 0.1, 1.5 }, { 0.76, 0.92 } } })
hl.curve("hyprnostretch", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.0 } } })
hl.curve("menu_decel", { type = "bezier", points = { { 0.1, 1 }, { 0, 1 } } })
hl.curve("menu_accel", { type = "bezier", points = { { 0.38, 0.04 }, { 1, 0.07 } } })
hl.curve("easeInOutCirc", { type = "bezier", points = { { 0.85, 0 }, { 0.15, 1 } } })
hl.curve("easeOutCirc", { type = "bezier", points = { { 0, 0.55 }, { 0.45, 1 } } })
hl.curve("easeOutExpo", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("softAcDecel", { type = "bezier", points = { { 0.26, 0.26 }, { 0.15, 1 } } })
hl.curve("md2", { type = "bezier", points = { { 0.4, 0 }, { 0.2, 1 } } })

-- hl.animation({ leaf = "windows", enabled = true, speed = 3, curve = "md3_decel", style = "popin 60%" })
-- hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, curve = "md3_decel", style = "popin 60%" })
-- hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, curve = "md3_accel", style = "popin 60%" })
-- hl.animation({ leaf = "border", enabled = true, speed = 10, curve = "default" })
-- hl.animation({ leaf = "fade", enabled = true, speed = 3, curve = "md3_decel" })
-- hl.animation({ leaf = "layersIn", enabled = true, speed = 3, curve = "menu_decel", style = "slide" })
-- hl.animation({ leaf = "layersOut", enabled = true, speed = 1.6, curve = "menu_accel" })
-- hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 2, curve = "menu_decel" })
-- hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 4.5, curve = "menu_accel" })
-- hl.animation({ leaf = "workspaces", enabled = true, speed = 10, curve = "menu_decel", style = "slide" })
-- hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3, curve = "md3_decel", style = "slidevert" })

-- --------------------------------------------------------------------------
-- Gestures
-- --------------------------------------------------------------------------
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
hl.gesture({ fingers = 3, direction = "up", action = "fullscreen" })
hl.gesture({ fingers = 3, direction = "down", action = "float" })

-- --------------------------------------------------------------------------
-- Devices
-- --------------------------------------------------------------------------
if profile == "laptop" then
    hl.device({
        name = "-usb-optical-mouse",
        left_handed = true,
    })
    hl.device({
        name = "etps/2-elantech-touchpad",
        sensitivity = 0.4,
    })
else
    hl.device({
        name = "dell-kb216-wired-keyboard",
        kb_layout = "br",
        kb_variant = "abnt2",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
    })
    hl.device({ name = "pixart-opticalmouse" })
end

-- --------------------------------------------------------------------------
-- Keybindings
-- --------------------------------------------------------------------------
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"),
    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
    { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set '10+'"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set '10-'"), { locked = true, repeating = true })

hl.bind("SUPER + Delete", hl.dsp.window.close())
hl.bind("SUPER + P", hl.dsp.window.pseudo())
hl.bind("SUPER + J", hl.dsp.layout("togglesplit"))
hl.bind("SUPER + K", hl.dsp.layout("swapsplit"))

hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("ALT + Tab", hl.dsp.exec_cmd("hyprctl dispatch cyclenext && hyprctl dispatch bringactivetotop"))
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + C",
    hl.dsp.exec_cmd("pkill fuzzel || cliphist list | fuzzel --match-mode=fzf --dmenu | cliphist decode | wl-copy"))

hl.bind("SUPER + Return", hl.dsp.exec_cmd(terminal .. " --window-size-pixels=100x100"))
hl.bind("SUPER + Backspace", hl.dsp.exec_cmd(terminal .. " --title=\"foot floating\""))
hl.bind("SUPER + SHIFT + Backspace", hl.dsp.exec_cmd(terminal .. " --title=\"foot floating\""))
hl.bind("ALT + Backspace", hl.dsp.exec_cmd(terminal .. " --title=\"foot floating\""))

hl.bind("SUPER + D", hl.dsp.exec_cmd("ags toggle launcher"))
hl.bind("Print", hl.dsp.exec_cmd("zoom.nu --type 'screenshot'"))
hl.bind("SUPER + Print", hl.dsp.exec_cmd("flameshot screen"))
hl.bind("SUPER + SHIFT + Print", hl.dsp.exec_cmd("hyprpicker --autocopy"))

hl.bind("SUPER + F", hl.dsp.exec_cmd("hyprctl dispatch fullscreen 0"))
hl.bind("SUPER + M", hl.dsp.exec_cmd("hyprctl dispatch fullscreen 1"))

hl.bind("SUPER + Minus", hl.dsp.exec_cmd("hyprctl dispatch layoutmsg splitratio -0.1"), { repeating = true })
hl.bind("SUPER + Equal", hl.dsp.exec_cmd("hyprctl dispatch layoutmsg splitratio 0.1"), { repeating = true })
hl.bind("SUPER + Semicolon", hl.dsp.exec_cmd("hyprctl dispatch layoutmsg splitratio -0.1"), { repeating = true })
hl.bind("SUPER + Apostrophe", hl.dsp.exec_cmd("hyprctl dispatch layoutmsg splitratio 0.1"), { repeating = true })

hl.bind("CONTROL + SUPER + right", hl.dsp.focus({ workspace = "+1" }))
hl.bind("CONTROL + SUPER + left", hl.dsp.focus({ workspace = "-1" }))
hl.bind("CONTROL + SUPER + Equal", hl.dsp.exec_cmd("zoom.nu --type 'in'"), { repeating = true })
hl.bind("CONTROL + SUPER + Minus", hl.dsp.exec_cmd("zoom.nu --type 'out'"), { repeating = true })

hl.bind("SUPER + SHIFT + Right", hl.dsp.exec_cmd("hyprctl dispatch movewindow mon:+1"))
hl.bind("SUPER + SHIFT + Left", hl.dsp.exec_cmd("hyprctl dispatch movewindow mon:-1"))

-- for i = 1, 10 do
-- 	local key = i % 10
-- 	hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = i }))
-- 	hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
-- end

-- --------------------------------------------------------------------------
-- Window rules
-- --------------------------------------------------------------------------
local function no_blur_rule(name, klaqss)
    hl.window_rule({
        name = "perf-no-blur-" .. name,
        match = { class = klass },
        no_blur = true,
    })
end

no_blur_rule("foot", "^(foot)(.*)$")
no_blur_rule("firefox", "^(firefox)(.*)$")
no_blur_rule("rnote", "^(rnote)(.*)$")
no_blur_rule("telegram", "^(telegram)(.*)$")
no_blur_rule("gimp", "^(gimp)(.*)$")
no_blur_rule("pavucontrol", "^(pavucontrol)(.*)$")
no_blur_rule("thunar", "^(thunar)(.*)$")
no_blur_rule("torrent", "^(torrent)(.*)$")
no_blur_rule("songrec", "^(SongRec)(.*)$")
no_blur_rule("thunderbird", "^(Thunderbird)(.*)$")
no_blur_rule("lxappearance", "^(Lxappearance)(.*)$")
no_blur_rule("qalculate", "^(Qalculate)(.*)$")

hl.window_rule({
    name = "perf-no-blur-mpv",
    match = { class = "^(mpv)(.*)$" },
    no_blur = true,
    content = "video",
    sync_fullscreen = true,
})

hl.window_rule({
    name = "anki-no-fullscreen",
    match = { class = ".*anki.*" },
    suppress_event = "maximize fullscreen",
})

hl.window_rule({
    name = "thunderbird-reminders",
    match = { class = "org.mozilla.Thunderbird", title = ".*Reminder.*" },
    float = true,
    size = "681 314",
    center = true,
})

hl.window_rule({
    name = "firefox-close-popup",
    match = { class = "^(firefox)(.*)$", title = "^(Close Firefox)$" },
    float = true,
    size = "(monitor_w/4) (monitor_h/8)",
    center = true,
})

hl.window_rule({
    name = "inkscape-import-dialog",
    match = { title = "^(png bitmap image import)" },
    float = true,
    center = true,
    size = "386 324",
})

hl.window_rule({
    name = "generic-dialogs",
    match = {
        title =
        "^(Media viewer|Export Image|Exportar imagem|Salvar imagem|Editando Conexao|Abrir arquivo|Import File|Select a File|Choose wallpaper|Open Folder|Save Document As|Save Image|Save As|Library|File Upload|Enter name of file|Enter name of file to save to|Save File|Open File)(.*)$",
    },
    float = true,
    size = "850 525",
    center = true,
})

hl.window_rule({
    name = "preferences-dialog",
    match = { title = "^(Preferences)(.*)$" },
    float = true,
    size = "900 700",
    center = true,
})

hl.window_rule({
    name = "olive-dialog",
    match = { title = "^(org\\.olivevideoeditor\\.Olive)(.*)$" },
    float = true,
})

hl.window_rule({
    name = "blob-dialog",
    match = { title = "^(blob:)(.*)$" },
    float = true,
})

hl.window_rule({
    name = "portal-dialog",
    match = { class = "xdg-desktop-portal-gtk" },
    float = true,
})

hl.window_rule({
    name = "file-save-extra",
    match = { title = "^(Save As|Abrir arquivo)(.*)$" },
    float = true,
    center = true,
})

hl.window_rule({
    name = "foot-floating-overlay",
    match = { title = "foot floating" },
    float = true,
    size = "550 425",
    center = true,
})

hl.window_rule({
    name = "xwayland-video-bridge",
    match = { class = "^(xwaylandvideobridge)$" },
    opacity = "0.0 override 0.0 override",
    no_anim = true,
    no_initial_focus = true,
    max_size = "1 1",
    no_blur = true,
})

hl.window_rule({
    name = "telegram-stay-focused",
    match = { class = "^(telegram)(.*)$" },
    stay_focused = true,
})

if profile == "laptop" then
    hl.window_rule({
        name = "flameshot-overlay",
        match = { title = "^(flameshot)" },
        float = true,
        move = "0 0",
    })
else
    hl.window_rule({
        name = "flameshot-overlay",
        match = { title = "^(flameshot)" },
        float = true,
        move = "(-1*monitor_w) 0",
        size = "(monitor_w*2) monitor_h",
        monitor = "HDMI-A-1",
        pin = true,
    })
end

-- --------------------------------------------------------------------------
-- Optional hyprsplit extras from previous Lua config
-- --------------------------------------------------------------------------
local has_hyprsplit, hs = pcall(require, "hyprsplit")
if has_hyprsplit then
    hs.config({ num_workspaces = 10 })
    hl.bind("SUPER + G", hs.dsp.grab_rogue_windows())
end
