---@diagnostic disable: undefined-global

hl.config({ autogenerated = false })

require("animations/index")
require("bind/index")
require("cursor/index")
require("debug/index")
require("decoration/index")
require("device/index")
require("dwindle/index")
require("ecosystem/index")
require("exec/index")
require("general/index")
require("gesture/index")
require("input/index")
require("master/index")
require("misc/index")
require("monitor/index")
require("render/index")
require("windowrule/index")
require("xwayland/index")

local function require_lua_tree(root)
    local handle = io.popen('/usr/bin/find -L ' .. root .. ' -maxdepth 2 -type f -name "*.lua"')
    if not handle then
        return
    end

    for path in handle:lines() do
        dofile(path)
    end

    handle:close()
end

require_lua_tree("~/.config/hypr/current")
