[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "o"
run = "shell 'xdg-open %h' --orphan"
desc = "Open with system default application"

[[mgr.prepend_keymap]]
on = ["<C-w>"]
run = "plugin close-and-restore-tab close_to_left"
desc = "Close the current tab and turn to left tab, or quit if it is last tab"

# [[mgr.prepend_keymap]]
# on = ["<C-w>"]
# run = "plugin close-and-restore-tab close_to_right"
# desc = "Close the current tab and turn to right tab, or quit if it is last tab"

[[mgr.prepend_keymap]]
on = ["<C-S-T>"]
run = "plugin close-and-restore-tab restore"
desc = "Restore the closed tab"

[[mgr.prepend_keymap]]
run = ["shell 'organize-fav.nu %h' --orphan", "ya emit reveal %h"]
on = ["<C-k>"]
desc = "Organize favorites with nu shell"

[[mgr.prepend_keymap]]
on = ["e"]
run = "shell '$EDITOR %h' --block"
desc = "Open with default editor"

[[mgr.prepend_keymap]]
on = ["P", "s"]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = ["P", "l"]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = ["P", "P"]
run = "plugin projects load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = ["P", "d"]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = ["P", "D"]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = ["P", "m"]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[mgr.prepend_keymap]]
on = ["P", "M"]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

[[mgr.prepend_keymap]]
on = ["<Space>"]
run = "toggle"
desc = "Toggle selection"
