$cursor-theme = Bibata-Rainbow-Modern
$cursor-size  = 32
# $gtk-theme    = Adwaita
# $icon-theme   = HighContrast
$style-theme  = prefer-dark

env = XCURSOR_SIZE,$cursor-size
env = XCURSOR_THEME,$cursor-theme
#env = THEME_DIR,/usr/share/themes/Adwaita

exec-once = hyprctl setcursor $cursor-theme $cursor-size
exec-once = gsettings set org.gnome.desktop.interface cursor-theme $cursor-theme
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursor-size
#exec-once = gsettings set org.gnome.desktop.interface gtk-theme $gtk-themek
#exec-once = gsettings set org.gnome.desktop.interface icon-theme $icon-theme
exec-once = gsettings set org.gnome.desktop.interface color-scheme $style-theme

cursor {
    zoom_disable_aa = true

    inactive_timeout = 4
    hide_on_tablet = true

    # To fix cursor not appearing when screen sharing:
    no_hardware_cursors = true
}
